name: React App CI/CD

on:
  push:
    branches:
      - main  # ทำงานเมื่อมีการ Push โค้ดเข้า branch main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # ⚠️ แก้ตรงนี้เป็นชื่อ Docker Hub ของมึง
          tags: boonyaritllennkim/React-dog-skin-disease:latest 

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # ⚠️ แก้ตรง your-username/your-repo-name ให้ตรงกับข้างบน
            docker pull boonyaritllennkim/React-dog-skin-disease:latest
            docker stop my-react-app || true
            docker rm my-react-app || true
            docker run -d --name my-react-app -p 80:80 boonyaritllennkim/React-dog-skin-disease:latest
